backend:
    name: github # Refer to https://www.netlifycms.org/docs/authentication-backends/ for auth backend list and instructions
    branch: master # Branch to update
    repo: movingoolong/moving-oolong # Repo for pushing new commits. Make sure to replace with your repo!

media_folder: static/assets
public_folder: assets

collections:
    - name: blog
      label: "Episode Posts"
      folder: "content/posts"
      create: true
      slug: "{{slug}}"
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Cover Image", name: "imgsrc", widget: "image" }
          - {
                label: "Category",
                name: "category",
                widget: "hidden",
                default: "episode",
            }
          - {
                label: "Tags",
                name: "tags",
                widget: "relation",
                collection: "options",
                file: "episode-tags",
                hint: "New tags can be added in the Editable Options collection",
                valueField: "options.*",
                searchFields: ["options.*"],
                default: "select",
                multiple: true,
            }
          - {
                label: "Embedded Link",
                name: "link",
                widget: "markdown",
                minimal: true,
            }
          - { label: "Body", name: "body", widget: "markdown" }
    - name: bios
      identifier_field: name
      label: "Bios"
      folder: "content/bios"
      create: false
      fields:
          - { label: "Name", name: "name", widget: "string" }
          - {
                label: "Category",
                name: "category",
                widget: "hidden",
                default: "bio",
            }
          - { label: "Profile Picture", name: "imgsrc", widget: "image" }
          - {
                label: "Instagram",
                name: "instagram",
                widget: "string",
                required: false,
                hint: "@name",
                pattern: ["@.+", "Must begin with an @ symbol"],
            }
          - {
                label: "Twitter",
                name: "twitter",
                widget: "string",
                required: false,
                hint: "@name",
                pattern: ["@.+", "Must begin with an @ symbol"],
            }
          - { label: "Body", name: "body", widget: "markdown" }
    - name: options
      label: "Editable Options"
      create: false
      folder: "content/options"
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
                label: "Category",
                name: "category",
                widget: "hidden",
                default: "options",
            }
          - {
                label: "Options",
                name: "options",
                allow_add: true,
                widget: "list",
                collapsed: false,
                hint: "Order of this list determines order on site where applicable. Spaces after commas will be automatically added",
            }
